// @no-log
// @no-redirect
// @no-cookie-jar
GET http://localhost:8080/api/v1/medicos
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
 });

 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
POST http://localhost:8080/api/v1/conselhos
Content-Type: application/json
Accept: application/json

{
  "nome": "CRdAC-{{$uuid}}"
}

> {%
 client.global.set("conselho", response.headers.valuesOf("Location")[0].match( /\d*$/ ));
 %}
###
POST http://localhost:8080/api/v1/medicos
Content-Type: application/json
Accept: application/json

{
  "numeroConselho": 123,
  "ufConselho": "SP",
  "conselho": {
  "idConselho": {{conselho}}
  }
}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
 });

 client.global.set("local", response.headers.valuesOf("Location")[0]);
 %}


###
// @no-log
// @no-redirect
// @no-cookie-jar
GET http://localhost:8080{{local}}
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 client.test("Request executed successfully", function() {
        client.assert(response.body.numeroConselho === 123 , "Número do conselho diferente");
        client.assert(response.body.ufConselho === 'SP' , "UF conselho diferente");
        client.assert(response.body.conselho.idConselho === {{conselho}} , "Id Conselho diferente");
    });
 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
PUT http://localhost:8080{{local}}
Content-Type: application/json
Accept: application/json

{
  "numeroConselho": 321,
  "ufConselho": "RJ",
  "conselho": {
  "idConselho": {{conselho}}
  }
}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
GET http://localhost:8080{{local}}
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 client.test("Request executed successfully", function() {
        client.assert(response.body.numeroConselho === 321 , "Número do conselho diferente");
        client.assert(response.body.ufConselho === 'RJ' , "UF conselho diferente");
        client.assert(response.body.conselho.idConselho === {{conselho}} , "Id Conselho diferente");
    });
 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
DELETE http://localhost:8080{{local}}
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
GET http://localhost:8080{{local}}
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
DELETE http://localhost:8080{{local}}
Accept: application/json

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 412, "Response status is not 412");
    });
 %}

###
// @no-log
// @no-redirect
// @no-cookie-jar
PUT http://localhost:8080{{local}}
Accept: application/json
Content-Type: application/json

{
  "numeroConselho": 123,
  "ufConselho": "SP",
  "conselho": {
  "idConselho": {{conselho}}
  }
}

> {%
 client.test("Request executed successfully", function() {
        client.assert(response.status === 412, "Response status is not 412");
    });
 %}
